version: '3.8'

volumes:
  ollama_storage:

networks:
  n8n_network:
    external: true

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    networks:
      - n8n_network
    ports:
      - "11434:11434"
    volumes:
      - ollama_storage:/root/.ollama
    gpus: all
    command: "ollama serve"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:11434/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3 