volumes:
  n8n_data:
  code_server_data:
  postgres_storage:
  qdrant_storage:
  ollama_storage:

networks:
  n8n_network:
    driver: bridge

services:
  # DATABASE
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    networks:
      - n8n_network
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-n8n}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-n8n}
      - POSTGRES_DB=${POSTGRES_DB:-n8n}
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U ${POSTGRES_USER:-n8n} -d ${POSTGRES_DB:-n8n}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: always
    networks:
      - n8n_network
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  # AI
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    networks:
      - n8n_network
    ports:
      - "11434:11434"
    volumes:
      - ollama_storage:/root/.ollama
    # Abilita esplicitamente il supporto GPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # APPLICAZIONI
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    networks:
      - n8n_network
    environment:
      - N8N_HOST=${N8N_HOST:-192.168.0.49}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - N8N_PATH=/
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB:-n8n}
      - DB_POSTGRESDB_USER=${POSTGRES_USER:-n8n}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD:-n8n}
      - N8N_EDITOR_BASE_URL=http://${N8N_HOST:-192.168.0.49}:5678
      - N8N_HOST_WEBHOOK_URL=http://${N8N_HOST:-192.168.0.49}:5678/webhook/
      - DB_POSTGRESDB_SCHEMA=public
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_SECURE_COOKIE=false
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres
      - qdrant
      - ollama

  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    restart: always
    networks:
      - n8n_network
    ports:
      - "8080:8080"
    volumes:
      - code_server_data:/home/coder/project/workspace
    environment:
      - PASSWORD=codeserver!2025

  # Qdrant UI
  qdrant-ui:
    image: qdrant/qdrant-ui:latest
    container_name: qdrant-ui
    restart: always
    networks:
      - n8n_network
    ports:
      - "6334:6334"
    environment:
      - VITE_QDRANT_URL=http://qdrant:6333

  # PostgreSQL Admin
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    networks:
      - n8n_network
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@tuodominio.it
      - PGADMIN_DEFAULT_PASSWORD=changeme
    ports:
      - "8081:80" 