version: '3.8'

volumes:
  n8n_data:
  nginx_ssl:
  code_server_data:

networks:
  n8n_network:
    external: true

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    networks:
      - n8n_network
    expose:
      - "5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - N8N_PATH=/
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=postgres
      - N8N_EDITOR_BASE_URL=https://${DOMAIN:-localhost}
      - N8N_HOST_WEBHOOK_URL=https://${DOMAIN:-localhost}/webhook/
      - DB_POSTGRESDB_SCHEMA=public
    ports:
      - "127.0.0.1:5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - ssl-generator

  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    restart: always
    networks:
      - n8n_network
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - code_server_data:/home/coder
      - ./code-server-project:/home/coder/workspace
    environment:
      - PASSWORD=codeserver!2025
      - DOCKER_USER=coder

  ssl-generator:
    build:
      context: ./nginx
    image: ssl-generator
    command: ["generate-ssl.sh", "${DOMAIN:-localhost}"]
    volumes:
      - nginx_ssl:/ssl
    networks:
      - n8n_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    networks:
      - n8n_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_ssl:/etc/nginx/ssl:ro
    depends_on:
      - n8n
      - ssl-generator 