version: '3.8'

volumes:
  n8n_storage:
  nginx_ssl:
  code_server_config:
  code_server_data:
  workspace_projects:

networks:
  n8n_network:
    external: true

services:
  code-server:
    build:
      context: ./code-server-project
      dockerfile: Dockerfile
    container_name: code-server
    restart: always
    networks:
      - n8n_network
    ports:
      - "8080:8080"  # Esponi code-server direttamente per debug
    environment:
      - TZ=Europe/Rome
      - PASSWORD=codeserver!2025
    volumes:
      - code_server_config:/home/coder/.config
      - code_server_data:/home/coder/project
      - workspace_projects:/home/coder/workspace
      - ./projects:/home/coder/workspace/n8n-project
    user: "0:0"  # Run as root to avoid permission issues
    gpus: all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    networks:
      - n8n_network
    ports:
      - "5678:5678"  # Esponi n8n direttamente per debug
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_USER=${POSTGRES_USER:-n8n}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD:-n8n}
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB:-n8n}
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_PERSONALIZATION_ENABLED=false
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY:-n8n-encryption-key}
      - N8N_USER_MANAGEMENT_JWT_SECRET=${N8N_USER_MANAGEMENT_JWT_SECRET:-n8n-jwt-secret}
      - OLLAMA_HOST=ollama:11434
      - N8N_HOST=0.0.0.0
      - N8N_PROTOCOL=http
      - N8N_PORT=5678
      - N8N_PATH=/
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./shared:/data/shared
    depends_on:
      - ssl-generator

  ssl-generator:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: ssl-generator
    volumes:
      - nginx_ssl:/etc/nginx/ssl
    networks:
      - n8n_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    networks:
      - n8n_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_ssl:/etc/nginx/ssl:ro
    depends_on:
      - ssl-generator 