volumes:
  ollama_storage:

networks:
  n8n_network:
    external: true

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    networks:
      - n8n_network
    ports:
      - "11434:11434"
    volumes:
      - ollama_storage:/root/.ollama
    # Abilita esplicitamente il supporto GPU
    gpus: all
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # Rimosso healthcheck per evitare problemi 