version: '3.8'

volumes:
  postgres_storage:
  qdrant_storage:

networks:
  n8n_network:
    external: true

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    networks:
      - n8n_network
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-n8n}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-n8n}
      - POSTGRES_DB=${POSTGRES_DB:-n8n}
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U ${POSTGRES_USER:-n8n} -d ${POSTGRES_DB:-n8n}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: always
    networks:
      - n8n_network
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage 