version: '3.8'

volumes:
  code_server_config:
  code_server_data:

services:
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - CODE_SERVER_PASSWORD=${CODE_SERVER_PASSWORD}
    volumes:
      - code_server_config:/home/coder/.config:rw
      - code_server_data:/home/coder/project:rw
      - ../:/home/coder/project/workspace:rw
    ports:
      - "8080:8080"
    user: "1000:1000"
    networks:
      - default 