version: '3.8'

services:
  code-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: code-server
    restart: always
    environment:
      - PASSWORD=${CODE_SERVER_PASSWORD:-changeme}
      - SUDO_PASSWORD=${CODE_SERVER_PASSWORD:-changeme}
    ports:
      - "8080:8080"
    volumes:
      - ..:/home/coder/project/workspace:rw

volumes:
  code_server_data: 