version: '3.8'

volumes:
  code_server_config:
  code_server_data:

services:
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    restart: always
    environment:
      - TZ=Europe/Rome
      - PASSWORD=codeserver!2025  # Fixed password
    volumes:
      - code_server_config:/home/coder/.config
      - code_server_data:/home/coder/project
      - ../:/home/coder/project/workspace
    ports:
      - "8080:8080"
    user: "0:0"  # Run as root to avoid permission issues 